### ISSUE TITLE
Create project from template

### ISSUE THREAD

**Issue by Zorin95670** [ditrit/leto-modelizer#131]
## Description

**As a** user in the homepage,

**I want** to select a template and specify the project's name and the model's name,

**so that** I can create a new project initialize with the content of the template.

**Comment by viennem** [comment]
> I want to select a template and specify the project name and the template's name,

the user does not specify the template's name after selecing it, it should be the model's name

**Comment by Catepeli** [comment]
"As a user in the projects view,"
What is "the project view"?

**Comment by Zorin95670** [comment]
The projet's view is the homepage with the list of all projets.

**Comment by Zorin95670** [comment]
Done in #187
