### ISSUE TITLE
Access to the index view from home page

### ISSUE THREAD

**Issue by Zorin95670** [ditrit/leto-modelizer#133]
## Description

**As a** user, in the homepage, after creating or importing project

**I want** to be in the index view (view containing the list model & model template)

**so that** I can manage the models of my project

**Comment by Catepeli** [comment]
The template's view is a new word, what is it?
Is it the page about the template ?
So is it the template's page , or the 'page index' ?

**Comment by k-y0u** [comment]
> The template's view is a new word, what is it? Is it the page about the template ? So is it the template's page , or the 'page index' ?

corrected

**Comment by Zorin95670** [comment]
Done in #187
