### ISSUE TITLE
Add git provider panel in the Text view

### ISSUE THREAD

**Issue by Mari0nV** [ditrit/leto-modelizer#22]
## Description

**As a** user,

**When** I am on the Text view and I have configured my git provider settings

**I want** to be able to browse my git repository and select a file

**so that** I can load its content into the Text editor.

## Acceptance Criteria

 **Scenario** | Git configuration is set and correct
 ------------ | -------------------------------------------------
 **Given**    | My git configuration is set and correct
 **When**     | I go the the Text view
 **Then**     | I can see a panel on the left with the list of my git repository files and folders
 **And**      | I can browse the content of the repository
**And**        | I can select a file and see its content in the Text editor

**Scenario** | Git configuration is incorrect (connection problem or something else)
 ------------ | -------------------------------------------------
 **Given**    | My git configuration is set but there is an issue
 **When**     | I go the the Text view
 **Then**     | a toast will appear to say there is an error with git provider

### Constraints

See scenarios

**Comment by Zorin95670** [comment]
Remove scenario:
```
**Scenario** | Git configuration is not set
 ------------ | -------------------------------------------------
 **Given**    | My git configuration is not set
 **When**     | I go the the Text view
 **Then**     | I can see a panel on the left with a message saying that I have to set my git config to load a file
```

because on project creation, we initialize git repository in local.
