### ISSUE TITLE
Links/References are broken when the target component is renamed

### ISSUE THREAD

**Issue by viennem** [ditrit/leto-modelizer#340]
**Describe the bug**

This bug occurs with `Link` attributes, and `Reference` attributes (container components).

1. **Link** attributes:
   `Given` I have a component with a Link attribute targeting another component,
   `When` I rename the target component,
   `Then` the Link attribute is not updated,
   `And` the link's svg line is frozen in place.

2. **Reference** attributes (container components):
   `Given` I have a component with a Reference attribute targeting a container component,
   `When` I rename the container component,
   `Then` the Reference attribute is not updated,
   `And` the nested component disappears.

There are no errors in the console when this bug happens.

This bug is caused by the absence of automatic update of `Link`/`Reference` attributes when a component is renamed.

**To Reproduce**

https://github.com/ditrit/leto-modelizer/assets/20184007/afeafa73-99e4-4267-9cdf-c6865437824c

**Expected behavior**

1. **Link** attributes:
   `Given` I have components with a Link attribute targeting a component,
   `When` I rename the target component,
   `Then` all the Link attributes targeting the renamed component should be automatically updated.

2. **Reference** attributes (container components):
   `Given` I have a components with a Reference attribute targeting a container component,
   `When` I rename the container component,
   `Then` all the Reference attributes targeting the renamed component should be automatically updated.

**Application**

- `leto-modelizer` version `1.2.0`

**Comment by Zorin95670** [comment]
Technical tasks:
- In plugin-core, create: 
  - method renameComponentId => change component id and all related id (link/container)
- In terrator-plugin: Check if we have to update something
- In leto-modelizer: update id field to use the new method
