### ISSUE TITLE
ArrayInput: Add element to array when switching focus without pressing ENTER

### ISSUE THREAD

**Issue by viennem** [ditrit/leto-modelizer#372]
**Describe the bug**

After entering text inside an ArrayInput, I have to press ENTER to add an element to the Array.

I expected the value to also be added to the Array if I switch focus without pressing ENTER, for example:

* When I focus another input in the ComponentDetailsPanel.
* When I click on an empty space in the draw view.
* When I focus another window in my operating system.
* When I click on the "SAVE" button.

**To Reproduce**

https://github.com/ditrit/leto-modelizer/assets/20184007/8a8554c4-ddb0-4155-ac59-de73538e7043

**Application**

- `leto-modelizer` commit hash: `f59e63e9d861fb5d0f0849dc7983be3a76bd779a`.

**Comment by Zorin95670** [comment]
We can't fix this problem, but we can display an hint to press enter to validate user value.

If, the problem persist, we have to brainstorm with our UX this field usage.
