### ISSUE TITLE
Drag & drop position has unexpected offset when the viewport is moved and then the draw view is reopened

### ISSUE THREAD

**Issue by viennem** [ditrit/leto-modelizer#373]
**Describe the bug**

Precondition: in the draw view, I move the viewport, then exit the draw view and reopen it.
When I drag & drop a new component from the ComponentDefinitionsDrawer, then the position of the new component is not the same as the position of my mouse cursor (there is an offset equal to the viewport move from the precondition).

**To Reproduce**

https://github.com/ditrit/leto-modelizer/assets/20184007/587f0fb2-0b36-48b7-bebe-599f61c255e7

**Application**

- `leto-modelizer` commit hash: `f59e63e9d861fb5d0f0849dc7983be3a76bd779a`.
- `leto-modelizer-plugin-core` version: `#0.19.0`.

**Comment by Zorin95670** [comment]
Create an init function in plugin-core to set tx/ty to 0 and another think.
