### ISSUE TITLE
Inaccessible menu with long file name

### ISSUE THREAD

**Issue by Reallnas** [ditrit/leto-modelizer#383]
**Describe the bug**

When I create a new file manually (using the "New File") or via the "render" function of a Leto Modelizer plugin, if the file name is too long, the three dots icon that enables us to delete the file is inaccessible.
When working in the root folder it is unlikely to have files with names this long but the problem is more apparent in subfolders and sub-subfolders of the root as the left bar has a fixed size.

**To Reproduce**

1. Go to the "Text" Tab
2. Click on the three dots next to the root folder then "New File"
3. Choose a long file name (something like "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" works)

**Expected behavior**

The three dots icon should be always present regardless of the file name size.

**Screenshots**

![image](https://github.com/ditrit/leto-modelizer/assets/96346088/7119a823-fa7f-4145-91eb-608bf73dbe08)

**Application (please complete the following information):**

- leto version [1.2.0]

**Desktop (please complete the following information):**

- OS: Linux
- Browser : Chromium and Firefox
- Version: Chromium (116.0.5845.96) / Firefox (116.0.3)

**Comment by Zorin95670** [comment]
ADd elispse and display file extension:
`aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.tf`
become:
`aaaaaaaaaaa....tf`
