### ISSUE TITLE
Delete project shortcut from home page

### ISSUE THREAD

**Issue by Mari0nV** [ditrit/leto-modelizer#39]
## Description

**As a** user,

**When** I am on the home page of the modelizer

**I want** to be able to delete a project shortcut from the home page

**so that**  I only keep the ones I want visible

## Acceptance Criteria

 **Scenario** | Delete project shortcut on home page
 ------------ | -------------------------------------------------
 **Given**    | A project card displayed on the home page
 **Then**     | I expect to be able to delete it

### Constraints

There will be a deletion button on the top right of each project card.

## Resources

![Capture d’écran 2022-07-27 à 15 34 03](https://user-images.githubusercontent.com/23618241/181260089-39bef4a5-7e75-4dec-844a-9cbc2ca35a3b.png)
:

**Comment by Zorin95670** [comment]
Done in #156
