### ISSUE TITLE
File explorer is broken when creating a folder with the same name as the root folder 

### ISSUE THREAD

**Issue by justinehell** [ditrit/leto-modelizer#393]
**Describe the bug**

File explorer is broken when creating a folder with the same name as the root folder. We can no longer create another file or folder.

**To Reproduce**

https://github.com/ditrit/leto-modelizer/assets/62500081/6042be98-b59a-4ef8-b8ad-ac53a75d02d6

**Expected behavior**

Be able to create the folder with the same name.

**Application :**

- leto version [1.2.0], commit hash 7276fca8f1a41a24ce925c5b6bf7c1bc34836282

**Comment by Faty2S** [comment]
LET-397 (was created as a US or it is a Bug on Jira) so now it becomes LET-414.
