### ISSUE TITLE
Handle multi-file compilation and display in Text view

### ISSUE THREAD

**Issue by Mari0nV** [ditrit/leto-modelizer#40]
## Description

**As a** user,

**When** I am on the Text view

**I want** to be able to open multiple files

**And** I want all of them to be compiled when switching on the Model view

**so that** I don't need to have all my project in one file only.

## Acceptance Criteria

 **Scenario** | Open multiple files from git repo
 ------------ | -------------------------------------------------
 **Given**    | A list of files in the git panel
 **When**     | I double click on an additional file
 **Then**     | I want a new tab to open that show this new file
 **And**      | I want previous selected files to still be on another tab
**And**       | I want all the files present in the tabs be compiled on switch
**And**       | I want to be able to close a tab, leading the corresponding file not to be compiled on switch

## Resources:

![Capture d’écran 2022-07-27 à 16 30 05](https://user-images.githubusercontent.com/23618241/181273637-2fa14d1d-1448-4c85-b80d-a6354c6e1730.png)

**Comment by Zorin95670** [comment]
Done by @justinehell
