### ISSUE TITLE
Investigate the feasibility of auto save with blur event

### ISSUE THREAD

**Issue by justinehell** [ditrit/leto-modelizer#403]
Investigate the feasibility of auto save with the blur event. Link to https://github.com/ditrit/leto-modelizer/issues/402

Handle close panel, close leto tab, click on draw area while changing data, switch to Text view etc..

**Comment by aboubakar14** [comment]
The blur event may not work, this one do not propagate the event to its parent (as in our case the inputs are in a panel).
In that case, the **focusout** event maybe the one we want. 

Test the focusout also
