### ISSUE TITLE
Handle the token expiration

### ISSUE THREAD

**Issue by aboubakar14** [ditrit/leto-modelizer#435]
## Description

As we can now, know, if a token is expired (or will be), we should properly handle the case in the SplashPage.js
If the token is expired, we should redo a login.
if the token is not expired, no need to redo the login.

But try not to make any more call than necessary to check if the token is expired or will be (only one call should be enough). Maybe, store in pinia or in local storage when the token will be expired?

**Comment by Zorin95670** [comment]
Done
